### ISSUE TITLE
[TypeScript] Module '"disqus-react"' has no exported member 'Recommendations' ts(2614)

### ISSUE THREAD

**Issue by lucascaton** [disqus/disqus-react#104]
`Recommendations` component was introduced in PR #94 (which is great!) but it doesn't seem to have type definitions ([like other components do](https://github.com/disqus/disqus-react/blob/master/types/index.d.ts)).

### To Reproduce  

Import the component:

```ts
import { Recommendations } from "disqus-react";
```

And this TypeScript error is displayed:

```
Module '"disqus-react"' has no exported member 'Recommendations'. ts(2614)
```

### Specifications:  
 - OS: macOS Big Sur (11.4)
 - Package version: 1.1.0
 - Node version: 14.17.0

**Comment by tterb** [comment]
@lucascaton Thanks for the report!
I should be able to get a PR up for this today.

**Comment by tterb** [comment]
@lucascaton I put up #105 to resolve this issue, but it would be great if you could take a look since I'm admittedly not very familiar with Typescript.

**Comment by lucascaton** [comment]
Just tested, all good @tterb. Thanks! 😃
