### ISSUE TITLE
<link ... in Head Tag Not Cleaned

### ISSUE THREAD

**Issue by renomureza** [disqus/disqus-react#108]
I'm using Nextjs, 

When I navigate from a page with no comments to a page with comments repeatedly, Disqus keeps inserting the <link... tag in <head>.

![image](https://user-images.githubusercontent.com/49445216/127798526-254819bc-1637-4dc4-9884-276961ab9884.png)

**Comment by tterb** [comment]
@renomureza Thanks for reporting this issue. It looks like there might be an issue with the cleanup process.
Do you have a public repo that I can use to reproduce this issue?

**Comment by renomureza** [comment]
Hi @tterb you can check it out here:
- https://codesandbox.io/s/next-disqus-eid24?file=/pages/with-disqus.js
- https://eid24.sse.codesandbox.io/

**Comment by tterb** [comment]
@renomureza I just put up a PR(#111) to fix this issue. It would be great if you could pull the branch and make sure that it resolves your problem before merging.

**Comment by renomureza** [comment]
> @renomureza I just put up a PR(#111) to fix this issue. It would be great if you could pull the branch and make sure that it resolves your problem before merging.

@tterb It works fine, in `<header>` it's clean.

But, I noticed at the end of the <body> tag there is an `<iframe>` which has the same behavior, not cleaned.

![image](https://user-images.githubusercontent.com/49445216/129467648-1277df27-a75a-4926-943d-ddfac45471eb.png)

**Comment by tterb** [comment]
@renomureza Nice catch!
I've updated the PR to also remove the referenced iframe.

**Comment by renomureza** [comment]
@tterb Yes it works, everything is as expected. 🥳

Waiting for release.

**Comment by tterb** [comment]
@renomureza Thanks for your help!
I'll try to get a new version of the package published to NPM later today.

**Comment by brokul-dev** [comment]
Hi!
I've updated `disqus-react` package to the newest version. Scripts from `head` and Disqus `iframe` are removed but there is still one `iframe` that is not deleted. Here is the result after few roundtrips:

![image](https://user-images.githubusercontent.com/78214221/130751844-49eb4267-8749-4424-9cd8-54e65aaa056f.png)

Worth noticing that these iframes do not have `title` attributes. This attribute is currently used as a query selector in the cleanup code. 

Perhaps it's a problem on my side? :slightly_smiling_face:

**Comment by tterb** [comment]
@renomureza @brokul-dev Unfortunately, due to the lack of attributes on that iframe there isn't really a way of targeting them for removal that wouldn't cause unintended consequences for any other iframes on the page.
