### ISSUE TITLE
Remove "Comments" string from the CommentCount component

### ISSUE THREAD

**Issue by mangelsnc** [disqus/disqus-react#11]
Hi!

I want to remove the "Comments" string that is rendered with the comments count, i just want the integer part. Exists any way to get only the number of comments? Without the "comments" word? For internationalization matters will be very useful too.

**Comment by mangelsnc** [comment]
Hi @ryanvalentin!

Thanks! It's just what I want!

**Comment by The-Code-Monkey** [comment]
I have changed all 3 of them on my site and its not updating its still saying comments after the number

**Comment by seanngpack** [comment]
@The-Code-Monkey Did you resolve the issue? Mine keeps the 'comments' string as well even after changing the settings. Maybe it has something to do with the info being cached somewhere?

**Comment by seanngpack** [comment]
@seanngpack Eventually my comments updated and it works now. I guess the answer is to give it time.
