### ISSUE TITLE
Add/Expose additional API offerings

### ISSUE THREAD

**Issue by jarodtaylor** [disqus/disqus-react#112]
### Is your feature request related to a problem? Please describe.  
It would be nice to be able to use other APIs available from Disqus (e.g. listMostActiveUsers, listMostLikedUsers, etc)

### Describe the solution you'd like  
Either a way to expose these APIs so we can build our own UI with the data, or create more exports for listMostActiveUsers, etc.

**Comment by tterb** [comment]
@jarodtaylor The endpoints you referenced are already exposed through the [Disqus API](https://disqus.com/api/docs/).
