### ISSUE TITLE
DiscussionEmbed fails PropType Check for config Object, complains for String

### ISSUE THREAD

**Issue by sysRoot** [disqus/disqus-react#113]
Disregard. I'm novice.

### Describe the bug  
DiscussionEmbed's config prop says it would like a string not an object, fails proptype check

### To Reproduce  
Run `disqus-react` as of 9/8/2021 @ 2PM EDT

### Expected behavior  
I expected Disqus-React's DiscussionEmbed to load, but config complained about it being an object, and that it should be a string. PropType check fails

### Screenshots  
![image](https://user-images.githubusercontent.com/414285/132560577-49a96964-83e8-4ce8-82eb-16481c7c08ed.png)

### Specifications:  
 - OS: Arch Linux
 - Package version: 1.1.2
 - Node version: 14.17.4

**Comment by tterb** [comment]
@sysRoot This is the expected behavior because the `config.identifier` is supposed to be a string.
