### ISSUE TITLE
 Incorrect Shortname (visit disqus.com/register)

### ISSUE THREAD

**Issue by canmingir** [disqus/disqus-react#118]
I am getting `Incorrect Shortname (visit disqus.com/register)` message at the top of forums, however, I can still send/receive message, I didn't setup anything special though

```
<DiscussionEmbed
      shortname="example"
      config={{
        url: "https://nucleoidjs.disqus.com",
        identifier: "learn-1",
        title: "Nucleoid: Low-code framework for JS",
      }}
  />
```

**Comment by CyberCyclone** [comment]
`shortname` needs to be what is specified in the admin dashboard. As in, "example" needs to be the shortname for your account. I suspect in your case it will be `nucleoidjs`.

**Comment by cmora** [comment]
@canmingir You have a wrong configuration. Should be:

`
<DiscussionEmbed
      shortname="nucleoidjs"
      config={{
        url: "https://nucleoidjs.com/this-is-the-url-of-your-article-or-content",
        identifier: "learn-1",
        title: "Nucleoid: Low-code framework for JS",
      }}
  />
`
