### ISSUE TITLE
Language support, category support

### ISSUE THREAD

**Issue by RajeevSiewnath** [disqus/disqus-react#12]
Can you maybe add language support (multilingual support for multilingual sites) and category_id support to the component? Also maybe typescript definitions would be a good idea, especially since not all functionality seems to be written down in the README file.

**Comment by joyfulelement** [comment]
Part of the enhancements: **language support** is now available in #66. This can be configured via the `language` property. See https://github.com/disqus/disqus-react/blob/7f08fc848035aff4de9dca08e678e9adcd3a437a/README.md#language-configuration for detail.

**Comment by tterb** [comment]
The language support has been added by #66 and support for category_id has been added by #67, so I'm going to close this out.
