### ISSUE TITLE
How do I get the image to load in the preview part of the Disqus homepage?

### ISSUE THREAD

**Issue by Jeydin** [disqus/disqus-react#123]
Like in this image (which is an image of an anime streaming site) they have these images
![image](https://user-images.githubusercontent.com/89167700/160916223-db12e035-d90d-49c3-b78e-184115c1a34e.png)

**Comment by tterb** [comment]
@Jeydin The images displayed on that page are retrieved from the page where the Disqus thread is embedded, so if the image isn't being detected on your website, I would recommend adding the following tag to your page `<head />` to ensure it can be detected correctly.

```
<meta property="og:image" content="IMAGE_URL">
```

**Comment by Jeydin** [comment]
Thanks! Turns out that I didn't even specify an image tag in my page `<head>`.
