### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by tobysmith568** [disqus/disqus-react#125]
### Is your feature request related to a problem? Please describe.  

Hey - my project is on React 18 and the peer dependency version of React in this project maxes out at 17.
This means I'm unable to install it without using the `--legacy-peer-deps` flag when npm-installing.

### Describe the solution you'd like  

Please can this library be updated to include support for React 18?

### Describe alternatives you've considered  

N/A.

### Additional context

N/A

**Comment by tterb** [comment]
@tobysmith568 Thanks for the callout! I just put up a PR to update the `peerDependencies` to support React 18.

**Comment by tobysmith568** [comment]
Thanks - I was tempted to raise a PR myself with that change in it but I wasn't sure if you guys would need to do some manual testing on your end or if you had some kind of process for things like this? I saw React 15.x in your devDependencies and wasn't sure how to handle that and prove 18.x was all fine.

**Comment by tterb** [comment]
PRs are always welcome!
To test, I just modified the `package.json` to require `react` and `react-dom` to use `18.x`, tested the components manually using the example site that's in the repo with `yarn start`, and ran the existing tests with `yarn test`. So there's definitely no special procedure or magic involved 🤣 .

Though, we probably should modify the CI check against all the supported React versions to ensure we maintain compatibility.
