### ISSUE TITLE
Weird bugs

### ISSUE THREAD

**Issue by The-Code-Monkey** [disqus/disqus-react#13]
So it is working on localhost/news/1. but when i go to the second news article which is localhost/news/2 it says `We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.`

how is this its running off of the same code it shouldnt be any different

**Comment by aleccool213** [comment]
👍

**Comment by aleccool213** [comment]
Same errors for me as well depending on the identifier I give it. Some work, some don't :(

**Comment by The-Code-Monkey** [comment]
How though, it doesn't make sense

**Comment by aleccool213** [comment]
Only thing I can think of (while not looking at the code one bit) is that there is a bug in the initialization of the component, it works for 1 but not many. Super weird indeed.

**Comment by aleccool213** [comment]
@The-Code-Monkey I may be able to look at it this weekend but I am looking for alternatives to this package for the time being. Time == 💰

**Comment by gastongouron** [comment]
up
