### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by mateusfg7** [disqus/disqus-react#147]
I just created a `DisqusComments` component and this error appear:

_component:_
```tsx
import { DiscussionEmbed } from 'disqus-react'
import { Post } from 'contentlayer/generated'

interface Props {
  post: Post
}

export const DisqusComments = ({ post }: Props) => {
  return (
    <div>
      <DiscussionEmbed
        shortname={String(process.env.DISQUS_SHORTNAME)}
        config={{
          url: `https://mateusf.vercel.app/post/${post.id}`,
          identifier: post.id, // Single post id
          title: post.title // Single post title
        }}
      />
    </div>
  )
}
```

_output:_
```
- error node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js (32:112) @ _inherits
- error Error [TypeError]: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:90:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:156:5)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:226:2)
    at (sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20063:1)
    at __webpack_require__ (/workspace/mfg-b/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/index.js:30:21)
    at (sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/index.js (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20118:1)
    at __webpack_require__ (/workspace/mfg-b/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/(blog)/post/[slug]/components/disqus-comments.tsx:7:70)
    at (sc_server)/./src/app/(blog)/post/[slug]/components/disqus-comments.tsx (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20563:1) {
  digest: undefined
}
null
```

### Screenshots  
![image](https://github.com/disqus/disqus-react/assets/40613276/6e9d6bbd-3665-40d5-8226-90d9e86df086)

### Specifications: 
**disqus-react**: 1.1.5
**react**: 18.2.0
**next**: 13.4.4
**typescript** 5.1.3

_* I am on a **Next.js** project_

**Comment by basant-rai** [comment]
Same error

**Comment by basant-rai** [comment]
Did you fix an issue??

> I just created a `DisqusComments` component and this error appear:
> 
> _component:_
> 
> ```tsx
> import { DiscussionEmbed } from 'disqus-react'
> import { Post } from 'contentlayer/generated'
> 
> interface Props {
>   post: Post
> }
> 
> export const DisqusComments = ({ post }: Props) => {
>   return (
>     <div>
>       <DiscussionEmbed
>         shortname={String(process.env.DISQUS_SHORTNAME)}
>         config={{
>           url: `https://mateusf.vercel.app/post/${post.id}`,
>           identifier: post.id, // Single post id
>           title: post.title // Single post title
>         }}
>       />
>     </div>
>   )
> }
> ```
> 
> _output:_
> 
> ```
> - error node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js (32:112) @ _inherits
> - error Error [TypeError]: Super expression must either be null or a function
>     at _inherits (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:90:15)
>     at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:156:5)
>     at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js:226:2)
>     at (sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/CommentCount.js (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20063:1)
>     at __webpack_require__ (/workspace/mfg-b/.next/server/webpack-runtime.js:33:42)
>     at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/index.js:30:21)
>     at (sc_server)/./node_modules/.pnpm/disqus-react@1.1.4_react-dom@18.2.0_react@18.2.0/node_modules/disqus-react/lib/index.js (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20118:1)
>     at __webpack_require__ (/workspace/mfg-b/.next/server/webpack-runtime.js:33:42)
>     at eval (webpack-internal:///(sc_server)/./src/app/(blog)/post/[slug]/components/disqus-comments.tsx:7:70)
>     at (sc_server)/./src/app/(blog)/post/[slug]/components/disqus-comments.tsx (/workspace/mfg-b/.next/server/app/(blog)/post/[slug]/page.js:20563:1) {
>   digest: undefined
> }
> null
> ```
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/40613276/244692220-6e9d6bbd-3665-40d5-8226-90d9e86df086.png)
> 
> ### Specifications:
> **disqus-react**: 1.1.5 **react**: 18.2.0 **next**: 13.4.4 **typescript** 5.1.3
> 
> _* I am on a **Next.js** project_

Did you fix an issue??

**Comment by basant-rai** [comment]
@mateusfg7 
I got the same problem. Did you fix an issue?

**Comment by mateusfg7** [comment]
@basant-rai not yet 😢

**Comment by specialblend** [comment]
@mateusfg7 try adding `"use client";` to your component file

**Comment by basant-rai** [comment]
@mateusfg7 yeah it works thank you.

**Comment by mateusfg7** [comment]
@specialblend this works, thanks.
