### ISSUE TITLE
developer mode flag

### ISSUE THREAD

**Issue by liesislukas** [disqus/disqus-react#16]
how about prop `developerMode={true/false}`?
Trying to load comments at localhost. Can't enter dev mode or add localhost as valid domain.

![image](https://user-images.githubusercontent.com/2733862/44903851-4ac35080-ad16-11e8-9191-31bfc0729a4d.png)

![image](https://user-images.githubusercontent.com/2733862/44903864-531b8b80-ad16-11e8-8a12-5949456bbd9b.png)

**Comment by afixoftrix** [comment]
Any updates on this? Need disqus to render on localhost please.

**Comment by midori0507** [comment]
@afixoftrix 
@liesislukas 
I managed to have this running on localhost, by giving the a fake URL to config, while giving it a real shortname
In config, instead of giving `url` as full URL (contain localhost), try to replace your `localhost` with your `DISQUS_SITENAME`


```
const disqusConfig = {
    url: NODE_ENV === 'development' ? `http://${DISQUS_SHORTNAME}${props.location.pathname}`: props.location.href,
    title: post.frontmatter.title,
    identifier: props.pageContext.slug
  }
```

**Comment by afixoftrix** [comment]
@midori0507 Thanks man. I was able to get it to work using your method on localhost.

**Comment by wahlforss** [comment]
@midori0507 

Could you explain this in a bit more detail? What is the DISQUS_SHORTNAME variable?

**Comment by midori0507** [comment]
> @midori0507
> 
> Could you explain this in a bit more detail? What is the DISQUS_SHORTNAME variable?

I think its a typo, should be `DISQUS_SITENAME`. Its the domain where you tend to deploy to for example `foobar.com`

**Comment by tterb** [comment]
A note has been added to the README with #38 that details the same functionality @midori0507 has suggested, so I'm going to close this issue.
