### ISSUE TITLE
Render CommentCount only for positive number of comments

### ISSUE THREAD

**Issue by janosh** [disqus/disqus-react#22]
Is there a way to have the `CommentCount` display different text or not at all if the number of comments is zero?

**Comment by ryanvalentin** [comment]
That's something you can configure in your Disqus admin settings: https://help.disqus.com/installation/customizing-comment-count-link-text

**Comment by janosh** [comment]
MThanks for the quick reply!

Is there a way to get just the number in order to determine the rendering of components around it?

**Comment by tterb** [comment]
@janosh Currently, there isn't a way to only receiving the number of comments by itself.
