### ISSUE TITLE
Clarify relationship with Disqus, the company

### ISSUE THREAD

**Issue by ZhangYiJiang** [disqus/disqus-react#3]
In the `package.json` description, this package is described as the official Disqus React package. However, this is not mentioned on the GitHub repo description, nor in the README file, and the package is not published under the Disqus GitHub Organization https://github.com/disqus. 

I think it would be useful to clarify how official this package is, and make it easier for developers to trust it out of the other Disqus React components that are out there.

**Comment by ryanvalentin** [comment]
Yep! We'll be transferring it shortly.

**Comment by ZhangYiJiang** [comment]
Hi! Is there any update on this issue? Also, could you kindly update `package.json` and create a new release on npm? Thanks in advance!

**Comment by dparkar** [comment]
+1

**Comment by greeeg** [comment]
Hi @ryanvalentin, any news concerning the ownership transfer to the @disqus GitHub organization? Btw, thanks for what you did with this package :)

**Comment by LeKoArts** [comment]
@ryanvalentin Any updates on that?

**Comment by ryanvalentin** [comment]
Repository is now part of the Disqus org, as is the NPM package!
