### ISSUE TITLE
Comment count not updating 

### ISSUE THREAD

**Issue by watawep23** [disqus/disqus-react#30]
Hi, I can't manage to show the comment count for some of my post. Comment count only shows when it has a comment and there's a newer post.
![image](https://user-images.githubusercontent.com/39287835/60142793-f978d600-97ed-11e9-8661-2647253ee5c2.png)

**Comment by watawep23** [comment]
It seems like there's a delay to update the current comment count. Do you know how to fix that?

**Comment by tterb** [comment]
@watawep23 Could you provide the steps to reproduce this issue?

**Comment by watawep23** [comment]
Hello, actually there are no steps to reproduce this issue, as soon as i load my post it shows no comment count for about 20 minutes or less.

My code looks like this:

```
const Post = (props) => {
    const {title, content, createdAt, imageUrl, userId: {name}, _id} = props.details;
    const newImgUrl = imageUrl.replace('\\', '/'); // replacing the \ in imageUrl to prevent questionmark in backgroundimage url
    const imgSrc = `${baseUrl()}/${newImgUrl}`;
    let preview = stripHTML(content).substr(0, DEFAULT_STR_LENGTH);

    if (stripHTML(content).length > DEFAULT_STR_LENGTH) {
        preview += '...';
    }

    const disqusShortname = '*****';
    const disqusConfig = {
        url: window.location.href,
        identifier: _id,
        title: title,
    };

    return (
        <article className={classes.Post}>
            <div className={classes.Post__date}>
                <p className={classes.Post__date_m}>{moment(createdAt).format('MMMM')}</p>
                <p className={classes.Post__date_y}>{moment(createdAt).format('YYYY')}</p>
                <p className={classes.Post__date_d}>{moment(createdAt).format('D')}</p>
            </div>
            <Link to={`/post/${slugify(title, {lower: true})}`} className={classes.Post__banner_link}>
                <div className={classes.Post__banner} style={{backgroundImage: `url(${imgSrc})`}}></div>
            </Link>
            <div className={classes.Post__content}>
                <h1 className={classes.Post__title}>
                    <Link to={`/post/${slugify(title, {lower: true})}`}>{title}</Link>
                </h1>
                <ul className={classes.Post__meta}>
                    <li>By: <strong>{name}</strong></li>
                    <li>
                        <Disqus.CommentCount shortname={disqusShortname} config={disqusConfig}>
                            Comments
                        </Disqus.CommentCount>
                    </li>
                </ul>
                <p className={classes.Post__preview}>{preview}</p>
            </div>
        </article>
    ); 
}
```

I'm using Create React App.

**Comment by tterb** [comment]
@watawep23 Thanks for info. I'll look into this tomorrow and see if I'm able to reproduce the issue and find a potential solution.

**Comment by tterb** [comment]
@watawep23 It appears that the following function in the `CommentCount` component might not be keeping the count updated like it's supposed to.  
```js
const queueResetCount = debounce(() => {
    if (window.DISQUSWIDGETS)
        window.DISQUSWIDGETS.getCount({ reset: true });
}, 300, false); // eslint-disable-line no-magic-numbers
```

I've labelled this as a bug and will work on finding a solution.

**Comment by tterb** [comment]
I looked deeper into this issue and it appears that the issue is that the `count.js` script that the `CommentCount` component relies on is not intended to update in realtime and can have a delay of up to 10 minutes.  

Nonetheless, I'm going to investigate potential options for providing more responsive comment count data, so I'm going to label this as an enhancement rather than a bug for now.

**Comment by watawep23** [comment]
@tterb Noted. Thank you for your help.

**Comment by positimo** [comment]
Hi! The comment count still seems inaccurate, is there any updates on this? Should this issue still be open if it's not fixed?

**Comment by tterb** [comment]
@positimo As I mentioned above, the `count.js` script that the `CommentCount` component relies on is heavily cached within the Disqus service.  
At this time there isn't an alternative way of retrieving a real-time comment count, but I have shared this concern with the team internally.

**Comment by positimo** [comment]
Right, OK, I was just surprised to not find this issue immediately although it's still pending..

**Comment by marcossilvabr** [comment]
Hi :)
Just wanted to know if we have any news on this or if is still an issue. On my side, it is not working properly and I don't know if this is still a bug or if I'm doing something wrong. Thanks

**Comment by Stumblor** [comment]
Yep, also an issue here. Comment counters not updating, calling

`DISQUSWIDGETS.getCount({ reset: true })`

has no effect.

**Comment by Ekbal41** [comment]
same issue 😔
