### ISSUE TITLE
social share links (twitter/fb) point to localhost and not my domain

### ISSUE THREAD

**Issue by dapperAuteur** [disqus/disqus-react#31]
### Describe the bug  
the link domain is localhost and NOT the site domain when the user clicks the social share links (twitter/facebook) within the disqus component.

### To Reproduce  
  1. Go to 'http://bit.ly/2KH3iYP'  
  2. Scroll down to 'comments at the bottom of the page'  
  3. Click on 'tweet or share'
  4. See opening window and link it creates in the social post.
  5. use link to go to page and see error

### Expected behavior  
I expect the share link to take the user to the page on my site  

### Screenshots  
[screenshot of sharable link address](http://bit.ly/2X2qmD6)

### Specifications:  
 - OS: osx 10.14.5
 - Package version: "^1.0.5"
 - Node version: v10.14.0

### Additional context  
I'm using it with gatsbyjs ver "^2.4.3"
using gatsby starter: https://gatsby-sseon-starter.netlify.com/

**Comment by tterb** [comment]
@dapperAuteur I followed the share links you mentioned and experienced the behavior you described. Could you provide the relevant code or a link to a public repository so I can try to track down the issue?

**Comment by tterb** [comment]
It looks like this issue has gone quiet, so I'm gonna close it for now.
