### ISSUE TITLE
Typescript definitions missing from package

### ISSUE THREAD

**Issue by PedroLamas** [disqus/disqus-react#32]
### Describe the bug  
I see that there is a typescript definitions file on the repo (the `.d.ts` file), but seems that is not being pushed on the package.

### To Reproduce  
  1. Create a new React app with typescript support (`npx create-react-app new-app --typescript`)
  2. Add the disqus-react package (`npm install disqus-react`)
  3. Usin VSCode, open `App.tsx` and import the module (`import Discus from 'disqus-react';`)
  4. See tooltip error on the imported part.

### Expected behavior  
Typescript definitions should load

### Screenshots  
![image](https://user-images.githubusercontent.com/85504/60347887-4c04ee80-99b6-11e9-833b-f9bb0ba4f35e.png)

### Specifications:  
 - OS: Windows 10 1903 (latest available version), running Ubuntu via WSL
 - Package version: 1.0.5
 - Node version: 12.4.0

### Additional context  
Looking at the package contents, seems that the `.d.ts` file is missing!

**Comment by ryanvalentin** [comment]
Looks like the latest changes just need to be published to npm. I'd like to use this as well!

**Comment by tterb** [comment]
@PedroLamas The PR containing the typescript definitions was just merged a few days ago, but I'm working on get the npm package updated today.

**Comment by tterb** [comment]
@PedroLamas @ryanvalentin 
[v1.0.6](https://www.npmjs.com/package/disqus-react) Published to npm

**Comment by PedroLamas** [comment]
Awesome, thank you for the quick fix on this matter!

**Comment by bandinopla** [comment]
im getting `Cannot find module 'disqus-react'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?` with `"disqus-react": "^1.1.5"` using typescript...
