### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by semyou** [disqus/disqus-react#42]
I get this when I run the module. I think you need to replace componentWillMount

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: DiscussionEmbed

**Comment by tterb** [comment]
@semyou I've just made a PR that replaces the renamed lifecycle methods in the two components that are triggering these warnings.
