### ISSUE TITLE
SSO Integration

### ISSUE THREAD

**Issue by Nikolay992** [disqus/disqus-react#44]
I'm introducing Disqus in my platform as Business Account and I need to integrate ti Single Sign On feature. Is it possible to add this feature? 

Should be okay adding the remote_auth_s3 and the public_key in the  getDisqusConfig function

**Comment by tterb** [comment]
@Nikolay992 Yes, there's actually already a PR(#17) for adding SSO integration that I've been meaning to review. I'll see if I can get the SSO credentials to test the PR so we can merge it asap.

**Comment by tterb** [comment]
@Nikolay992 Are you able to confirm that adding the `remote_auth_s3` and `api_key` attributes to the config (as in #17) fixes the issue with your SSO integration?

**Comment by tterb** [comment]
Fixed with #17
