### ISSUE TITLE
misleading demo code at homepage

### ISSUE THREAD

**Issue by liesislukas** [disqus/disqus-react#60]
troubleshooting says that URLs must match, while code hints that it should be url to article. So which option is the correct one? Should it be url to article or homepage?

![image](https://user-images.githubusercontent.com/2733862/75777467-b39de580-5d5e-11ea-8db7-04fdf3cf6490.png)

the issue is that in any case, comments are not loading and there is no related issues in console or else.

![image](https://user-images.githubusercontent.com/2733862/75777736-2a3ae300-5d5f-11ea-89e9-72925031e5c5.png)

**Comment by tterb** [comment]
Hey @liesislukas, the intention of that message was to clear up confusion around users attempting to use their local `https://localhost:8000/path-to-article` URL in the config.  
Though now that you bring it up I can see how the wording could be potentially misleading.  

I will update the copy in the README with a more descriptive explanation.
