### ISSUE TITLE
Add onReady and other callbacks supported by Disqus

### ISSUE THREAD

**Issue by poohitan** [disqus/disqus-react#61]
Disqus supports more than only `onNewComment` callback, e.g. `onReady`, `onInit`, `onPaginate`, etc. It would be very useful to add and document these callbacks.

**Comment by poohitan** [comment]
I'm ready to prepare a PR if repo maintainer approve.

**Comment by tterb** [comment]
@poohitan PRs are always welcome!
Tag me when you submit the PR and I can review it.

**Comment by poohitan** [comment]
@tterb submitted a PR

**Comment by poohitan** [comment]
@tterb when do you plan to publish the last version on NPM?

**Comment by tterb** [comment]
@poohitan I'm hoping to get a new version published by the end of the week.
