### ISSUE TITLE
The comments thread is empty

### ISSUE THREAD

**Issue by buxzee** [disqus/disqus-react#70]
I have installed this plugin on my gatsby site, the widget appears but the comments are zero in all posts. The site is hosted on a temporary domain but I tried to pass the short name and the original site URL combination as given below: 

Here slug is the post slug 

```
const siteUrl = 'https://www.domain.com/' + slug
const disqusprops = {
shortname: 'shortname',
config: { identifier: siteUrl, title },
};

<DiscussionEmbed
 shortname={disqusprops.shortname}
 config={disqusprops.config}
/>
```

Please advise what am I doing wrong, how can I fix this issue so that the post associated comments can be displayed.

**Comment by tterb** [comment]
@buxzee I believe the issue might be that you are sending the `siteUrl` as the `identifier`, rather than the `url`. Though you will want to ensure that you specify the same config values on your gatsby site that you do on the original site.

**Comment by tterb** [comment]
Since this issue has gone silent, I'm going to assume that this was resolved and close it for now.
