### ISSUE TITLE
shouldComponentUpdate bug

### ISSUE THREAD

**Issue by bekju** [disqus/disqus-react#74]
### Describe the bug  
Even if the same props are passed the DiscussionEmbed rerenders.

### To Reproduce  
  1. Add discussion embed component with props
2. rerender the parent component of discussion embed
3.  even if the same props are passed it rerenders the whole component (new iframe loads)

### Expected behavior  
in shouldComponentUpdate `this.props === nextProps` will always return false even if same values (which goes to shallowComparison then).
To fix replace it with something like `this.props.identifier === nextProps.identifier && this.props.url === nextProps.url`

I think there's a problem with shallowComparison.

**Comment by tterb** [comment]
@bekju Thanks for reporting the issue, I'll take a look and try to track down the issue in `shallowComparison` function.

**Comment by tterb** [comment]
@bekju I believe I was able to locate the source of the issue and have created a PR(#75) with a fix. Would you be able to pull that branch and ensure that it resolves your issue?
