### ISSUE TITLE
TS Error: Statements not allowed in ambient contexts

### ISSUE THREAD

**Issue by bsgreenb** [disqus/disqus-react#82]
### Describe the bug  
```../node_modules/disqus-react/types/index.d.ts:7:2 - error TS1036: Statements are not allowed in ambient contexts.  7 };```

### To Reproduce  
Import disqus-react on TS, unless there's some special integration bug going on.

### Expected behavior  
Should not have type error.

### Screenshots  
![image](https://user-images.githubusercontent.com/980217/94651886-fea8b880-02ad-11eb-8d3b-8eeff2834d7a.png)

### Specifications:  
 - OS: Mac OS X
 - Package version: 1.0.8
 - Node version: 12.8.1
- TypeScript version: 3.8.3

**Comment by tterb** [comment]
@bsgreenb Thanks for reporting the issue!
Feel free to submit a PR if you have a solution to the problem, otherwise, I can probably look into it over the weekend.

**Comment by tterb** [comment]
This should be resolved by #105
