### ISSUE TITLE
won't work with react 17

### ISSUE THREAD

**Issue by natnaelawel** [disqus/disqus-react#85]
how to work with react version 17

**Comment by GoldinGuy** [comment]
Same issue here

**Comment by timtnleeProject** [comment]
Hi @natnaelawel ,
I use `"react": "17.0.1"` and it works,
what problem or error did you encountered?

**Comment by tterb** [comment]
@natnaelawel As @timtnleeProject mentioned, we're gonna need some more specific information to help you troubleshoot your issue.

**Comment by tterb** [comment]
I'm assuming that this might've been confusion over React v17 not being listed as a peer-dependency in the `package.json` which has been fixed in #88, so I'm gonna close this out for now.

**Comment by joshuaavalon** [comment]
@tterb Is there any information on when on it will be released? I am using npm@7 which changes on how it handles peer dependency and I need the update to stop it from complaining.

**Comment by tterb** [comment]
@joshuaavalon I just published the patch so v1.0.11 should be available now.
