### ISSUE TITLE
Can't set categories for my posts

### ISSUE THREAD

**Issue by SalahAdDin** [disqus/disqus-react#90]
### Describe the bug  
We are passing the categories to the post by the settings and it is not reflected on the **Disqus** dashboard.

### To Reproduce  
  1. First, setup the next code:
```javascript
  <DiscussionEmbed
              shortname={DISQUS_SHORT_NAME}
              config={{
                url: postURL,
                identifier: slug,
                title: titleEn,
                /*
                Must be
                First tag: category
                Others: order does not matter
                */
                category_id: DISQUS_CATEGORIES[tags[0]?.slug],
              }}
            />
```
where: 
```javascript
const DISQUS_CATEGORIES = {
  general: "8664428",
  "front-end": "8755878",
  "back-end": "8755881",
  "deep-learning": "8755886",
  "video-games": "8755887",
}
```
  2. Publish a new blog on your site with _front-end_ as first tag., it uses **NextJS** `10.0.5`. 
  3. Go to the dashboard, Tools > Discussions.
  4. The new post will have _General_ as its category.
 
### Expected behavior  
As the first tag _front-end_, we should see it as the discussions category.

### Specifications:  
 - OS: OsX.
 - Package version: 1.0.10.
 - Node version: 12.x.

**Comment by tterb** [comment]
@SalahAdDin Thanks for the report.
It looks like the package isn't configured to handle the category variable and pass it to the `disqus_config`. It shouldn't take too much work to add this functionality, so I can try to put up a PR in the next couple days.

**Comment by SalahAdDin** [comment]
@tterb Thank you!

**Comment by tterb** [comment]
@SalahAdDin I just noticed that the package actually does allow you to pass the category ID, but the param is camel-case (ie: `categoryID` instead of `category_id`).

**Comment by SalahAdDin** [comment]
> @SalahAdDin I just noticed that the package actually does allow you to pass the category ID, but the param is camel-case (ie: `categoryID` instead of `category_id`).

Oh, my mistake them, let me check.

**Comment by tterb** [comment]
@SalahAdDin I'm gonna assume that this solution worked and close this out, but you can reopen the issue if you're still experiencing issues.

**Comment by SalahAdDin** [comment]
@tterb `categoryId` or `categoryID` (first one is more camelCase)?
